name: Docker Image CI

on:
  push:
    branches: [ "main", "chore/add-github-workflow" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
   
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag liatrio-apprentice:${{ github.run_number }}

    - name: Run the Docker container
      run: docker run -d -p 80:3000 liatrio-apprentice:${{ github.run_number }}

    - name: Run Apprentice Action
      uses: liatrio/github-actions/apprentice-action@0b41561cca6822cc8d880fe0e49e7807a41fdf91
